### ISSUE TITLE
Give option to localize for different Amazon websites (amazon.co.jp, amazon.de, amazon.co.uk...)

### ISSUE THREAD

**Issue by emk2203** [asherAgs/amzSear#2]
For non-US Amazon users, the prices are meaningless. Please enable an option to specify which country should be the default for the query.

**Comment by asherAgs** [comment]
Hi emk2203! The second version of amzSear will be released soon with, among other improvements, the feature to specify a region both on the CLI and using the Python API.

**Comment by asherAgs** [comment]
This issue has been resolved in the v2 release. Closing this thread.
