### ISSUE TITLE
add cssselect to requirements.txt

### ISSUE THREAD

**Issue by KarlFiabeschi** [asherAgs/amzSear#3]
as subject: i tryed to create a aur package, but I discovered that there is also dependency on cssselect module.

**Comment by asherAgs** [comment]
Hi KarlFiabeschi,

If I'm not mistaken cssselect is encapsulated in the LXML module, which is the only dependency for amzSear. The separate cssselect module is not necessary.

**Comment by KarlFiabeschi** [comment]
> If I'm not mistaken cssselect is encapsulated in the LXML module
not at least in arch linux: 

https://www.archlinux.org/packages/extra/any/python-cssselect/
https://www.archlinux.org/packages/extra/x86_64/python-lxml/

btw i create a aur package if you are interested:

https://aur.archlinux.org/packages/amzsear/

**Comment by asherAgs** [comment]
Thanks for creating the package KarlFiabeschi! I really appreciate it.
